module.exports = {
    baseFile: 'themes/adwaita.theme.css',
    buildFile: 'build/adwaita.css',
    buildImport: '/* BUILD_IMPORT */',
    displayName: 'adwaita-discord',
    sourceFiles: [
        'icons.css',
        'scrollbars.css',
        'root.css',
        'global.css',
        'app-layout.css',
        'window-controls.css',
        'chatbar-editor.css',
        'notices.css',
        'buttons.css',
        'form-controls.css',
        'tabs.css',
        'chat-header.css',
        'toolbar.css',
        'dm-list.css',
        'channel-sidebar.css',
        'server-list.css',
        'user-panel.css',
        'members.css',
        'theme-editor.css',
        'voice-controls.css',
        'attachments.css',
        'embeds.css',
        'media-players.css',
        'messages.css',
        'chatbar.css',
        'modals.css',
        'quickswitcher.css',
        'profiles.css',
        'settings.css',
        'autocomplete.css',
        'inbox.css',
        'popouts.css',
        'search.css',
        'threads.css',
        'tooltips.css',
        'cards.css',
        'status-menu.css',
        'profile-popout.css',
        'vencord.css',
        'overrides.css',
        'bd.css'
    ],
};
